import {
  TWITCH_API_BASE_URL,
  TWITCH_API_CHEERMOTES_ENDPOINT,
  TWITCH_API_USERS_ENDPOINT,
} from '../../lib/constants/twitch-api'

const CHEERMOTES_PATH = `${TWITCH_API_BASE_URL}/${TWITCH_API_CHEERMOTES_ENDPOINT}`
const USERS_PATH = `${TWITCH_API_BASE_URL}/${TWITCH_API_USERS_ENDPOINT}`
const OTHER_PATH = `${TWITCH_API_BASE_URL}/*`

export { CHEERMOTES_PATH, USERS_PATH, OTHER_PATH }
