import {
  TWITCH_API_CHANNELS_ENDPOINT,
  TWITCH_API_CHEERMOTES_ENDPOINT,
  TWITCH_API_TOP_GAMES_ENDPOINT,
  TWITCH_API_USERS_ENDPOINT,
} from '../../lib/constants'
import { buildApiUrl } from '../../lib/utils'

const CHANNELS_PATH = buildApiUrl(TWITCH_API_CHANNELS_ENDPOINT)
const CHEERMOTES_PATH = buildApiUrl(TWITCH_API_CHEERMOTES_ENDPOINT)
const TOP_GAMES_PATH = buildApiUrl(TWITCH_API_TOP_GAMES_ENDPOINT)
const USERS_PATH = buildApiUrl(TWITCH_API_USERS_ENDPOINT)
const OTHER_PATH = buildApiUrl('*')

export { CHANNELS_PATH, CHEERMOTES_PATH, TOP_GAMES_PATH, USERS_PATH, OTHER_PATH }
