const TWITCH_API_ENDPOINT = 'https://api.twitch.tv/helix/'
const TWITCH_CLIENT_ID = process.env.REACT_APP_TWITCH_CLIENT_ID || ''
const TWITCH_MOCK_API_ENDPOINT = '/mock/'

export { TWITCH_API_ENDPOINT, TWITCH_CLIENT_ID, TWITCH_MOCK_API_ENDPOINT }
